Bulky.WebUI/Areas/Admin/Controllers/OrderController.cs
using System.Security.Claims;
using BulkyBook.DataAccess.Abstracts;
using BulkyBook.Models.Masters;
using BulkyBook.Models.ViewModels;
using BulkyBook.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Stripe;

namespace BulkyBook.WebUI.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize]
public class OrderController : Controller
{
    [BindProperty]
    public OrderVM OrderVM { get; set; }

    private readonly IUnitOfWork _unitOfWork;
    private readonly IWebHostEnvironment _webHostEnvironment;

    public OrderController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
    {
        _unitOfWork = unitOfWork;
        _webHostEnvironment = webHostEnvironment;
    }


    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Details(int orderId)
    {
        OrderVM = new OrderVM
        {
            OrderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == orderId, includeProperties: nameof(_unitOfWork.ApplicationUser)),
            OrderDetails = _unitOfWork.OrderDetail.GetAll(x => x.OrderHeaderId == orderId, includeProperties: nameof(_unitOfWork.Product))
        };

        return View(OrderVM);
    }

    [HttpPost]
    [Authorize(Roles = SD.Role.Admin + "," + SD.Role.Employee)]
    public IActionResult UpdateOrderHeader()
    {
        var existingOrder = _unitOfWork.OrderHeader.Get(x => x.Id == OrderVM.OrderHeader.Id) ?? throw new Exception("Order now found.");

        existingOrder.Name = OrderVM.OrderHeader.Name;
        existingOrder.PhoneNumber = OrderVM.OrderHeader.PhoneNumber;
        existingOrder.StreetAddress = OrderVM.OrderHeader.StreetAddress;
        existingOrder.City = OrderVM.OrderHeader.City;
        existingOrder.State = OrderVM.OrderHeader.State;
        existingOrder.PostalCode = OrderVM.OrderHeader.PostalCode;

        if (!string.IsNullOrEmpty(OrderVM.OrderHeader.Carrier))
            existingOrder.Carrier = OrderVM.OrderHeader.Carrier;
        if (!string.IsNullOrEmpty(OrderVM.OrderHeader.TrackingNumber))
            existingOrder.TrackingNumber = OrderVM.OrderHeader.TrackingNumber;


        _unitOfWork.OrderHeader.Update(existingOrder);
        _unitOfWork.SaveChanges();

        TempData["Success"] = "Order has been updated successfully.";

        return RedirectToAction(nameof(Details), new { orderId = existingOrder.Id });
    }

    [HttpPost]
    [Authorize(Roles = SD.Role.Admin + "," + SD.Role.Employee)]
    public IActionResult StartProcessing()
    {
        _unitOfWork.OrderHeader.UpdateStatus(OrderVM.OrderHeader.Id, SD.OrderStatus.InProcess);
        _unitOfWork.SaveChanges();

        TempData["Success"] = "Order has been updated successfully.";

        return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });
    }

    [HttpPost]
    [Authorize(Roles = SD.Role.Admin + "," + SD.Role.Employee)]
    public IActionResult ShipOrder()
    {
        var existingOrder = _unitOfWork.OrderHeader.Get(x => x.Id == OrderVM.OrderHeader.Id);
        existingOrder.TrackingNumber = OrderVM.OrderHeader.TrackingNumber;
        existingOrder.Carrier = OrderVM.OrderHeader.Carrier;
        existingOrder.OrderStatus = SD.OrderStatus.Shipped;
        existingOrder.ShippingDate = DateTime.Now;

        if (existingOrder.PaymentStatus == SD.PaymentStatus.DelayedPayment)
            existingOrder.PaymentDueDate = DateOnly.FromDateTime(DateTime.Now.AddDays(30));

        _unitOfWork.OrderHeader.Update(existingOrder);
        _unitOfWork.SaveChanges();

        TempData["Success"] = "Order has been shipped successfully.";

        return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });
    }

    [HttpPost]
    [Authorize(Roles = SD.Role.Admin + "," + SD.Role.Employee)]
    public IActionResult CancelOrder()
    {
        var existingOrder = _unitOfWork.OrderHeader.Get(x=>x.Id == OrderVM.OrderHeader.Id);

        if (existingOrder.PaymentStatus == SD.PaymentStatus.Approved)
        {
            var options = new RefundCreateOptions
            {
                Reason = RefundReasons.RequestedByCustomer,
                PaymentIntent = existingOrder.PaymentIntentId
            };

            var service = new RefundService();
            Refund refund = service.Create(options);

            _unitOfWork.OrderHeader.UpdateStatus(existingOrder.Id, SD.OrderStatus.Cancelled, SD.PaymentStatus.Refunded);
        }
        else
        {
            _unitOfWork.OrderHeader.UpdateStatus(existingOrder.Id, SD.OrderStatus.Cancelled, SD.OrderStatus.Cancelled);
        }
        _unitOfWork.SaveChanges();

        TempData["Success"] = "Order has been cancelled successfully.";

        return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });

    }

    #region API CALLS

    [HttpGet]
    public IActionResult GetAll(string status)
    {
        IEnumerable<OrderHeader> orderHeaders = new List<OrderHeader>();

        if (User.IsInRole(SD.Role.Admin) || User.IsInRole(SD.Role.Employee))
        {
            orderHeaders = _unitOfWork.OrderHeader
            .GetAll(includeProperties: nameof(_unitOfWork.ApplicationUser));
        }
        else
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            if (claimsIdentity.IsAuthenticated == false)
            {
                return Json(new { data = orderHeaders });
            }
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            orderHeaders = _unitOfWork.OrderHeader
                .GetAll(x => x.ApplicationUserId == userId, includeProperties: nameof(_unitOfWork.ApplicationUser));
        }

        switch (status)
        {
            case "pending":
                orderHeaders = orderHeaders.Where(u => u.PaymentStatus == SD.PaymentStatus.DelayedPayment);
                break;
            case "inprocess":
                orderHeaders = orderHeaders.Where(u => u.OrderStatus == SD.OrderStatus.Pending);
                break;
            case "completed":
                orderHeaders = orderHeaders.Where(u => u.OrderStatus == SD.OrderStatus.Shipped);
                break;
            case "approved":
                orderHeaders = orderHeaders.Where(u => u.OrderStatus == SD.OrderStatus.Approved);
                break;
            default:
                break;
        }

        return Json(new { data = orderHeaders });
    }

    [HttpDelete]
    public IActionResult Delete(int? id)
    {
        OrderHeader? orderHeader = _unitOfWork.OrderHeader.Get(x => x.Id == id);
        if (orderHeader == null)
            return Json(new { success = false, message = "Error while deleting, Order id not found." });

        //var oldImageUrl = orderHeader.ImageUrl;
        //if (!string.IsNullOrEmpty(oldImageUrl))
        //{
        //    string wwwRootPath = _webHostEnvironment.WebRootPath;
        //    //delete the old image
        //    var oldImagePath = Path.Combine(wwwRootPath, oldImageUrl.TrimStart('\\'));
        //    if (System.IO.File.Exists(oldImagePath))
        //    {
        //        System.IO.File.Delete(oldImagePath);
        //    }
        //}

        _unitOfWork.OrderHeader.Remove(orderHeader);
        _unitOfWork.SaveChanges();

        return Json(new { success = true, message = "Delete successful." });
    }

    #endregion
}

Bulky.WebUI/Areas/Admin/Controllers/UserController.cs
using BulkyBook.DataAccess.Abstracts;
using BulkyBook.DataAccess.Base;
using BulkyBook.Models.Identity;
using BulkyBook.Models.Masters;
using BulkyBook.Models.ViewModels;
using BulkyBook.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using static BulkyBook.Utilities.SD;

namespace BulkyBook.WebUI.Areas.Admin.Controllers.Masters;

[Area("Admin")]
[Authorize(Roles = SD.Role.Admin)]
public class UserController : Controller
{
    private const string Company_Image_Path = @"images\companys";
    private readonly IUnitOfWork _unitOfWork;
    private readonly UserManager<IdentityUser> _userManager;
    private readonly RoleManager<IdentityRole> _roleManager;

    public UserController(
        IUnitOfWork unitOfWork,
        UserManager<IdentityUser> userManager,
        RoleManager<IdentityRole> roleManager)
    {
        _unitOfWork = unitOfWork;
        _userManager = userManager;
        _roleManager = roleManager;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult RoleManagement(string userId)
    {

        ApplicationUser user = _unitOfWork.ApplicationUser.Get(x => x.Id == userId, includeProperties: "Company");
        user.Role = _userManager.GetRolesAsync(user).GetAwaiter().GetResult().FirstOrDefault();

        List<IdentityRole> roles = _roleManager.Roles.ToList();
        IEnumerable<Company> companies = _unitOfWork.Company.GetAll();

        RoleManagementVM roleVM = new RoleManagementVM
        {
            User = user,
            RoleList = roles.Select(i => new SelectListItem(i.Name, i.Name)),
            CompanyList = companies.Select(i => new SelectListItem(i.Name, i.Id.ToString()))
        };

        return View(roleVM);
    }

    [HttpPost]
    public IActionResult RoleManagement(RoleManagementVM roleVM)
    {
        var oldRole = _userManager.GetRolesAsync(roleVM.User).GetAwaiter().GetResult().FirstOrDefault();

        ApplicationUser user = _unitOfWork.ApplicationUser.Get(x => x.Id == roleVM.User.Id);

        if (roleVM.User.Role != oldRole)
        {
            //Role was updated
            if (roleVM.User.Role == SD.Role.Company)
            {
                user.CompanyId = roleVM.User.CompanyId;
            }
            if (oldRole == SD.Role.Company)
            {
                user.CompanyId = null;
            }

            _unitOfWork.ApplicationUser.Update(user);
            _unitOfWork.SaveChanges();

            _userManager.RemoveFromRoleAsync(user, oldRole).GetAwaiter().GetResult();
            _userManager.AddToRoleAsync(user, roleVM.User.Role).GetAwaiter().GetResult();
        }
        else if (oldRole == SD.Role.Company && user.CompanyId != roleVM.User.CompanyId)
        {
            user.CompanyId = roleVM.User.CompanyId;

            _unitOfWork.ApplicationUser.Update(user);
            _unitOfWork.SaveChanges();
        }

        return RedirectToAction(nameof(Index));
    }


    #region API CALLS

    [HttpGet]
    public IActionResult GetAll()
    {
        IEnumerable<ApplicationUser> users = _unitOfWork.ApplicationUser.GetAll(includeProperties: nameof(_unitOfWork.Company));

        foreach (var user in users)
        {
            user.Role = _userManager.GetRolesAsync(user).GetAwaiter().GetResult().FirstOrDefault();

            if (user.Company == null)
            {
                user.Company = new Company { Name = "" };
            }
        }

        return Json(new { data = users });
    }

    [HttpPost]
    public IActionResult LockUnlock([FromBody] string id)
    {
        ApplicationUser? user = _unitOfWork.ApplicationUser.Get(x => x.Id == id);
        if (user == null)
            return Json(new { success = false, message = "Error while Locking/Unlocking." });

        string message = "";
        if (user.LockoutEnd != null && user.LockoutEnd > DateTime.Now)
        {
            //user is currently locked and we need to unlock them
            user.LockoutEnd = DateTime.Now;
            message = "User is unlocked now.";
        }
        else
        {
            //lock user for 7 days
            user.LockoutEnd = DateTime.Now.AddDays(7);
            message = "User is locked for 7 days.";
        }

        _unitOfWork.ApplicationUser.Update(user);
        _unitOfWork.SaveChanges();

        return Json(new { success = true, message = message });
    }

    #endregion
}

Bulky.WebUI/Controllers/Masters/CategoryController.cs
using BulkyBook.DataAccess.Abstracts;
using BulkyBook.DataAccess.Abstracts.Masters;
using BulkyBook.DataAccess.Base;
using BulkyBook.Models.Masters;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBook.WebUI.Controllers.Masters;
public class CategoryController : Controller
{
    private readonly IUnitOfWork _unitOfWork;

    public CategoryController(
        IUnitOfWork unitOfWork
        )
    {
        _unitOfWork = unitOfWork;
    }
    public IActionResult Index()
    {
        IEnumerable<Category> categories = _unitOfWork.Category.GetAll();

        return View(categories);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(Category category)
    {
        if (category.CategoryName == category.CategoryDisplayOrder.ToString())
        {
            ModelState.AddModelError(nameof(category.CategoryName), "Display Order cannot exactly match the Category Name.");
            return View();
        }

        if (!ModelState.IsValid)
        {
            return View(category);
        }

        var existingcategory = _unitOfWork.Category.GetFirstOrDefault(x => x.CategoryName == category.CategoryName);
        if (existingcategory != null && existingcategory.CategoryName == category.CategoryName)
        {
            ModelState.AddModelError(nameof(category.CategoryName), "Category Name already exists.");
            return View();
        }


        _unitOfWork.Category.Add(category);
        _unitOfWork.SaveChanges();

        TempData["Success"] = "Category created successfully.";

        return RedirectToAction("Index");
    }

    public IActionResult Edit(int? categoryId)
    {
        if (categoryId is null or 0)
            return NotFound();

        //Category? category = _dbContext.Categories.Find(categoryId);
        Category? category = _unitOfWork.Category.GetFirstOrDefault(x => x.CategoryId == categoryId);
        if (category == null)
            return NotFound();

        return View(category);
    }

    [HttpPost]
    public IActionResult Edit(Category category)
    {
        if (category.CategoryName == category.CategoryDisplayOrder.ToString())
        {
            ModelState.AddModelError(nameof(category.CategoryName), "Display Order cannot exactly match the Category Name.");
            return View();
        }

        if (!ModelState.IsValid)
        {
            return View(category);
        }

        _unitOfWork.Category.Update(category);
        _unitOfWork.SaveChanges();

        TempData["Success"] = "Category updated successfully.";

        return RedirectToAction("Index");
    }

    public IActionResult Delete(int? categoryId)
    {
        if (categoryId is null or 0)
            return NotFound();

        //Category? category = _dbContext.Categories.Find(categoryId);
        Category? category = _unitOfWork.Category.GetFirstOrDefault(x => x.CategoryId == categoryId);
        if (category == null)
            return NotFound();

        return View(category);
    }

    [HttpPost, ActionName("Delete")]
    public IActionResult DeletePOST(int? categoryId)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }
        Category? category = _unitOfWork.Category.GetFirstOrDefault(x => x.CategoryId == categoryId);
        if (category == null)
            return NotFound();

        _unitOfWork.Category.Remove(category);
        _unitOfWork.SaveChanges();

        TempData["Success"] = "Category deleted successfully.";

        return RedirectToAction("Index");
    }
}

Bulky.WebUI/ViewComponents/ShoppingCartViewComponent.cs
using System.Security.Claims;
using BulkyBook.DataAccess.Abstracts;
using BulkyBook.Utilities;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBook.WebUI.ViewComponents;

public class ShoppingCartViewComponent : ViewComponent
{
    private readonly IUnitOfWork _unitOfWork;

    public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var claimsIdentity = (ClaimsIdentity)User.Identity;
        var userIdClaim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

        if (userIdClaim == null)
        {
            HttpContext.Session.Clear();
            return View(0);
        }

        if(HttpContext.Session.GetInt32(SD.Session.ShoppingCart) != null)
        {
            return View(HttpContext.Session.GetInt32(SD.Session.ShoppingCart));
        }

        HttpContext.Session.SetInt32(SD.Session.ShoppingCart, _unitOfWork.ShoppingCart.GetAll(u =>
            u.ApplicationUserId == userIdClaim.Value).Count());

        return View(HttpContext.Session.GetInt32(SD.Session.ShoppingCart));
    }
}

Bulky.WebUI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bulky Book</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.dark.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/2.1.3/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" href="~/BulkyBook.WebUI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">
                    <img src="/images/book.png" style="width:30px;" alt="Company Logo" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole(SD.Role.Admin))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Order</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Management
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create User</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">Manage User</a>
                                    </li>
                                </ul>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                @await Component.InvokeAsync("ShoppingCart")
                            </a>
                        </li>

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="PartialViews/_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary text-muted">
        <div class="container">
            &copy; 2024 - Bulky Book - Made with <i class="bi bi-heart-fill text-danger"></i> by DotNetTution  - <a class="link-light" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.tiny.cloud/1/tvtw483fstn9igr0pkjdywfa2ssa1x3y0ljqduonw1afs5p1/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="//cdn.datatables.net/2.1.3/js/dataTables.min.js" type="text/javascript"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>